name: Deploy Frontend
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            img

      - name: "Azure login"
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: "Replace API URL in javascript"
        run: |
          ENV_API_URL=$(az keyvault secret show \
            --name "$prod-api-url" \
            --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)
          sed -i "s|{{API_URL}}|$ENV_API_URL|g" ./resume.js

      - name: "Upload to blob storage"
        uses: azure/cli@v2
        with:
          inlineScript: |
            STORAGE_NAME=$(az keyvault secret show \
              --name "prod-storage-account-name" \
              --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)
            STORAGE_KEY=$(az keyvault secret show \
              --name "prod-storage-account-key" \
              --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)
            az storage blob upload-batch \
              --account-name "$STORAGE_NAME" \
              --auth-mode key \
              --account-key "$STORAGE_KEY" \
              --destination '$web' \
              --source . \
              --overwrite

      - name: "Purge CDN endpoint"
        uses: azure/cli@v2
        with:
          inlineScript: |
            CDN_PROFILE=$(az keyvault secret show \
              --name "prod-cdn-profile" \
              --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)
            CDN_ENDPOINT=$(az keyvault secret show \
              --name "prod-cdn-endpoint" \
              --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)
            RESOURCE_GROUP=$(az keyvault secret show \
              --name "prod-resource-group" \
              --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query value -o tsv)        
            az cdn endpoint purge \
              --content-paths "/*" \
              --profile-name "$CDN_PROFILE" \
              --name "$CDN_ENDPOINT" \
              --resource-group "$RESOURCE_GROUP"